### ISSUE TITLE
Lobby National Ideas do not match UI alignment

### ISSUE THREAD

**Issue by BigBoss618** [Coyote-31/eu4_mod_Royal_Eagle_UI#1]
https://prnt.sc/xguesp as the title says.  I am including a screenshot to help you understand what the issue is. I am NOT running a mod that alters UI.

**Comment by Coyote-31** [comment]
Thanks for the screenshot, What is your resolution 1920x1080 ?

**Comment by BigBoss618** [comment]
Yes, 1920x1080p

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Coyote-31** [comment]
Do you have Emperor DLC ?

**Comment by BigBoss618** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Coyote-31** [comment]
I dont have it ><' so it is maybe why I can't see it in my game. 
I need to check in the code to know why the layout change in your game. 
Thanks for the report I am gonna try to fix it this week but as I can't reproduce the bug it's gonna be tricky !

**Comment by BigBoss618** [comment]
Pirate the game temporarily or borrow it from a friend who has it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Coyote-31** [comment]
Or maybe you have a mod that modify the frontend.gui file ?
Can you try to modify the load order of your mods in the launcher to see if there is any differences ?
Because nothing is correct when I closely look at your screenshot. Speaking of screenshot can you give me one with all your screen in that frontend page where you select the country, it could help me a bit to understand.
Thanks

**Comment by Coyote-31** [comment]
Good idea ! Haha piracy damn it's sad that you are right...

**Comment by BigBoss618** [comment]
Of course I will do that tomorrow.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Coyote-31** [comment]
Ok. I just give you a reference to see what it should be looks like on select screen when it is working : [Screenshot](https://steamuserimages-a.akamaihd.net/ugc/1752431099068387927/19529402D2CFBBAF3BAD5DBCBEC7A40505A6FE08/)

**Comment by BigBoss618** [comment]
Gotcha

**Comment by BigBoss618** [comment]
Sorry I forgot about this, will send the pictures in a bit!

**Comment by BigBoss618** [comment]
Ya ok it happened once i activated Idea Groups Expanded. 
In terms of its UI, IGE only adds a main menu window that tracks which Expanded Mods one has active (now obsolete). If I remove it, will it be fixed ?

**Comment by Coyote-31** [comment]
Ok so you are a modder too ! =)

Exactly, I had check your mod and the `frontend.gui` file is the compatibility problem between our two mods.
So if it has become useless because it is now obsolete the better is to delete this file. The frontend.gui is a huge file that manage a lot of screen before you start the game so I have to maintain it in my mod.

I have to check but maybe, as you add new ideas, the ideas select view is not displayed properly.

**Comment by BigBoss618** [comment]
Ya I will remove it asap, I am currently busy launching a new mod called Flavor Universalis, maybe we can collab on it !

**Comment by Coyote-31** [comment]
Like I thought there is a little problem with the scrollbar in the ideas view because there is more than 6 ideas by group :

![image](https://user-images.githubusercontent.com/39368766/105633418-b2831480-5e58-11eb-89f5-ba535e35ab71.png)

I can fix this in my next update.

Thanks for the proposition of collaboration but I don't really have time to spend on other mod for now. However I can still help if you struggle with interface but I don't know about scripts. And you can if you want use parts of my mod as it is under MIT license.

**Comment by BigBoss618** [comment]
This happens without your mod as well however I am no UI expert and therefore I do not know if I can fix it or how 😃

**Comment by BigBoss618** [comment]
I appreciate your hand of help and I thank you!

**Comment by Coyote-31** [comment]
> https://prnt.sc/xguesp as the title says. I am including a screenshot to help you understand what the issue is. I am NOT running a mod that alters UI.

For that 1st report : This bug appended if you dont have the file `frontend.gui` from my mod while loading the sprite for _selected country background_ from my mod.
